---
# This is a sample database file for the ActiveRecord ORM
:development: &defaults
  :adapter: mysql
  :database: playground_devel
  :username: pg_devel_user
  :password: pg_d3v3l
  :host: 10.0.0.1

:test:
  <<: *defaults
  :database: playground_test
  :username: pg_test_user
  :password: pg_t3st

:production:
  <<: *defaults
  :database: sample_production
  :username: playground_user
  :password: s!22@j24
