# This file is autogenerated. Instead of editing this file, please use the
# migrations feature of ActiveRecord to incrementally modify your database, and
# then regenerate this schema definition.

ActiveRecord::Schema.define(:version => 1) do

  create_table "blogposts", :force => true do |t|
    t.column "body", :text, :default => "", :null => false
    t.column "posted", :datetime, :null => false
    t.column "user", :string, :limit => 45, :default => "dstar", :null => false
    t.column "title", :string, :limit => 45, :default => "", :null => false
  end

  create_table "chapters", :force => true do |t|
    t.column "story_id", :integer, :limit => 10, :default => 0, :null => false
    t.column "number", :integer, :limit => 10, :default => 0, :null => false
    t.column "words", :integer, :limit => 10, :default => 0, :null => false
    t.column "date", :date, :null => false
    t.column "file", :string, :limit => 45, :default => "", :null => false
  end

  add_index "chapters", ["story_id", "number"], :name => "chap_uniq", :unique => true

  create_table "credits", :force => true do |t|
    t.column "user_id", :integer, :default => 0, :null => false
    t.column "story_id", :integer, :default => 0, :null => false
    t.column "credit_type", :string, :default => "Author", :null => false
  end

  create_table "monthlybystory", :id => false, :force => true do |t|
    t.column "story_id", :integer, :limit => 10, :default => 0, :null => false
    t.column "ord", :integer, :limit => 10, :default => 0, :null => false
    t.column "title", :string, :default => "", :null => false
    t.column "universe_id", :integer, :limit => 10, :default => 0, :null => false
    t.column "month", :integer
    t.column "year", :integer
    t.column "target_words", :integer, :limit => 28, :default => 0, :null => false
    t.column "wordcount", :float, :limit => 33
    t.column "overage", :float, :limit => 34
  end

  create_table "paragraphs", :force => true do |t|
    t.column "chapter_id", :integer, :limit => 10, :default => 0, :null => false
    t.column "body", :text, :default => "", :null => false
    t.column "order", :integer, :limit => 10, :default => 1, :null => false
    t.column "flag", :integer, :limit => 10, :default => 0, :null => false
  end

  create_table "pcomments", :force => true do |t|
    t.column "paragraph_id", :integer, :limit => 10, :default => 0, :null => false
    t.column "body", :text, :default => "", :null => false
    t.column "posted", :datetime, :null => false
    t.column "username", :string, :limit => 45, :default => "no user", :null => false
    t.column "flag", :integer, :limit => 10, :default => 0, :null => false
  end

  create_table "sessions", :force => true do |t|
    t.column "sessid", :string
    t.column "data", :text
    t.column "updated_at", :datetime
  end

  add_index "sessions", ["sessid"], :name => "session_index"

  create_table "stories", :force => true do |t|
    t.column "title", :string, :default => "", :null => false
    t.column "description", :text, :default => "", :null => false
    t.column "flag", :integer, :limit => 10, :default => 0, :null => false
    t.column "universe_id", :integer, :limit => 10, :default => 0, :null => false
    t.column "short_title", :string, :limit => 45, :default => "", :null => false
    t.column "order", :integer, :limit => 10, :default => 0, :null => false
    t.column "file_prefix", :string, :limit => 45, :default => "", :null => false
  end

  create_table "styles", :force => true do |t|
    t.column "element", :text, :default => "", :null => false
    t.column "definition", :text, :default => "", :null => false
    t.column "theme", :text, :default => "", :null => false
    t.column "user", :integer, :limit => 8, :default => 0, :null => false
  end

  create_table "targets", :force => true do |t|
    t.column "story_id", :integer, :limit => 10, :default => 0, :null => false
    t.column "month", :integer, :limit => 10, :default => 0, :null => false
    t.column "year", :integer, :limit => 10, :default => 0, :null => false
    t.column "weekly_words", :integer, :limit => 10, :default => 2000, :null => false
  end

  create_table "universes", :force => true do |t|
    t.column "universe", :string, :limit => 45, :default => "", :null => false
    t.column "description", :text, :default => "", :null => false
    t.column "flag", :integer, :limit => 10, :default => 0, :null => false
  end

end
